install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('sf')
install.packages('raster')
install.packages('tmap')
install.packages('fields')
